disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - identifier_name
opt_in_rules: # some rules are only opt-in
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - WebScraping
  - .gitignore
  - .travis.yml
  - GoogleService-Info.plist
  - Podfile
  - Podfile.lock
  - README
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

line_length: 180

type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)