language: swift
xcode_project: Feather.xcodeproj # path to your xcodeproj folder
xcode_scheme: FeatherTests

branches:
  only:
   - master
before_install:
   - brew install ruby
   - gem install cocoapods
   - gem install xcpretty -N
   - brew update
   - brew install swiftlint || true
script: 
   - xcodebuild -workspace Feather.xcworkspace -scheme | xcpretty -c
   - swiftlint
